;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-pair-delete-pair
        emmet-expand-line
        indent-for-tab-command
        kill-region
        markdown-cycle
        markdown-outdent-or-delete
        ns-copy-including-secondary
        rjsx-electric-lt
        write-file
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        handle-switch-frame
        helm-find-files
        mark-whole-buffer
        ))
